### ISSUE TITLE
Do you consider porth to have a packaging and published on pypi?

### ISSUE THREAD

**Issue by MUSANGTARA0** [tsoding/porth#18]
**Because i want to contribute to porth, i might be able to work on packaging**

**Comment by MUSANGTARA0** [comment]
Current prototype: https://github/MUSANGTARA0/porth

**Comment by rexim** [comment]
@MUSANGTARA0 no. The plan is to eventually completely get rid of Python and rewrite Porth in itself. Python is just a temporary language.

**Comment by MUSANGTARA0** [comment]
Alright
