### ISSUE TITLE
Discrepancy between com and sim modes for handling utf-8 characters.

### ISSUE THREAD

**Issue by vipulbhj** [tsoding/porth#19]
In compile mode, we are using `len` on the token value directly, which means we are not considering the size difference introduced by utf-8 characters, which was handled in simulation mode, but you missed that in compilation mode.

**Comment by vipulbhj** [comment]
#20 Attempts to fix this. 

I have not updated the tests since I am not sure how to type anything utf-8

😅😅😅

**Comment by rexim** [comment]
@vipulbhj nice catch! Thank you so much for reporting this!
