### ISSUE TITLE
`compile_tokens_to_program`  there's no need to reverse the tokens

### ISSUE THREAD

**Issue by drocha87** [tsoding/porth#58]
I just realized that there's no need to reverse the tokens since you can just `tokens.pop(0)` and `tokens = macros[token.value].tokens + tokens` when you need to append the list of tokens to `tokens` (in case of expanding a macro for example). 

I don't know if this can bring any performance improvements but I think it simplifies the code a little bit. 

If you want I can change the code and send a PR.

**Comment by ap29600** [comment]
reversing was actually a choice made keeping in mind the algorithmic complexity of the program, since pop(0) is O(n) but pop() is O(1).

**Comment by drocha87** [comment]
Ohh I didn't know about that. Holy molly good to know that `pop(0)` is `O(n)`.
