### ISSUE TITLE
x86_64 push only accepts immidiate 32bit

### ISSUE THREAD

**Issue by RobertBendun** [tsoding/porth#7]
[Push instruction](https://www.felixcloutier.com/x86/push) supports only 8,16 and 32 bit immidiate values. To push 64 bit, value must be stored in register e.g.
```asm
mov rax, 8589934592
push rax
```

Relevant code
https://github.com/tsoding/porth/blob/0b4afffec0d8a6db51a685cd3565eca5952e0794/porth.py#L286-L287

**Comment by rexim** [comment]
@RobertBendun yep, I also ran into this issue recently! Thanks for reporting it!
